package fix

import "time"

type forksResponse struct {
	Id        int    `json:"id"`
	Message   string `json:"message"`
	FullName  string `json:"full_name"`
	HumanName string `json:"human_name"`
	Url       string `json:"url"`
	Namespace struct {
		Id      int    `json:"id"`
		Type    string `json:"type"`
		Name    string `json:"name"`
		Path    string `json:"path"`
		HtmlUrl string `json:"html_url"`
	} `json:"namespace"`
	Path  string `json:"path"`
	Name  string `json:"name"`
	Owner struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"owner"`
	Assigner struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"assigner"`
	Description         string    `json:"description"`
	Private             bool      `json:"private"`
	Public              bool      `json:"public"`
	Internal            bool      `json:"internal"`
	Fork                bool      `json:"fork"`
	HtmlUrl             string    `json:"html_url"`
	SshUrl              string    `json:"ssh_url"`
	ForksUrl            string    `json:"forks_url"`
	KeysUrl             string    `json:"keys_url"`
	CollaboratorsUrl    string    `json:"collaborators_url"`
	HooksUrl            string    `json:"hooks_url"`
	BranchesUrl         string    `json:"branches_url"`
	TagsUrl             string    `json:"tags_url"`
	BlobsUrl            string    `json:"blobs_url"`
	StargazersUrl       string    `json:"stargazers_url"`
	ContributorsUrl     string    `json:"contributors_url"`
	CommitsUrl          string    `json:"commits_url"`
	CommentsUrl         string    `json:"comments_url"`
	IssueCommentUrl     string    `json:"issue_comment_url"`
	IssuesUrl           string    `json:"issues_url"`
	PullsUrl            string    `json:"pulls_url"`
	MilestonesUrl       string    `json:"milestones_url"`
	NotificationsUrl    string    `json:"notifications_url"`
	LabelsUrl           string    `json:"labels_url"`
	ReleasesUrl         string    `json:"releases_url"`
	Recommend           bool      `json:"recommend"`
	Gvp                 bool      `json:"gvp"`
	Homepage            string    `json:"homepage"`
	Language            string    `json:"language"`
	ForksCount          int       `json:"forks_count"`
	StargazersCount     int       `json:"stargazers_count"`
	WatchersCount       int       `json:"watchers_count"`
	DefaultBranch       string    `json:"default_branch"`
	OpenIssuesCount     int       `json:"open_issues_count"`
	HasIssues           bool      `json:"has_issues"`
	HasWiki             bool      `json:"has_wiki"`
	IssueComment        bool      `json:"issue_comment"`
	CanComment          bool      `json:"can_comment"`
	PullRequestsEnabled bool      `json:"pull_requests_enabled"`
	HasPage             bool      `json:"has_page"`
	License             string    `json:"license"`
	Outsourced          bool      `json:"outsourced"`
	ProjectCreator      string    `json:"project_creator"`
	Members             []string  `json:"members"`
	PushedAt            time.Time `json:"pushed_at"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	Parent              struct {
		Id        int    `json:"id"`
		FullName  string `json:"full_name"`
		HumanName string `json:"human_name"`
		Url       string `json:"url"`
		Namespace struct {
			Id      int    `json:"id"`
			Type    string `json:"type"`
			Name    string `json:"name"`
			Path    string `json:"path"`
			HtmlUrl string `json:"html_url"`
		} `json:"namespace"`
		Path  string `json:"path"`
		Name  string `json:"name"`
		Owner struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"owner"`
		Assigner struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"assigner"`
		Description         string      `json:"description"`
		Private             bool        `json:"private"`
		Public              bool        `json:"public"`
		Internal            bool        `json:"internal"`
		Fork                bool        `json:"fork"`
		HtmlUrl             string      `json:"html_url"`
		SshUrl              string      `json:"ssh_url"`
		ForksUrl            string      `json:"forks_url"`
		KeysUrl             string      `json:"keys_url"`
		CollaboratorsUrl    string      `json:"collaborators_url"`
		HooksUrl            string      `json:"hooks_url"`
		BranchesUrl         string      `json:"branches_url"`
		TagsUrl             string      `json:"tags_url"`
		BlobsUrl            string      `json:"blobs_url"`
		StargazersUrl       string      `json:"stargazers_url"`
		ContributorsUrl     string      `json:"contributors_url"`
		CommitsUrl          string      `json:"commits_url"`
		CommentsUrl         string      `json:"comments_url"`
		IssueCommentUrl     string      `json:"issue_comment_url"`
		IssuesUrl           string      `json:"issues_url"`
		PullsUrl            string      `json:"pulls_url"`
		MilestonesUrl       string      `json:"milestones_url"`
		NotificationsUrl    string      `json:"notifications_url"`
		LabelsUrl           string      `json:"labels_url"`
		ReleasesUrl         string      `json:"releases_url"`
		Recommend           bool        `json:"recommend"`
		Gvp                 bool        `json:"gvp"`
		Homepage            string      `json:"homepage"`
		Language            string      `json:"language"`
		ForksCount          int         `json:"forks_count"`
		StargazersCount     int         `json:"stargazers_count"`
		WatchersCount       int         `json:"watchers_count"`
		DefaultBranch       string      `json:"default_branch"`
		OpenIssuesCount     int         `json:"open_issues_count"`
		HasIssues           bool        `json:"has_issues"`
		HasWiki             bool        `json:"has_wiki"`
		IssueComment        bool        `json:"issue_comment"`
		CanComment          bool        `json:"can_comment"`
		PullRequestsEnabled bool        `json:"pull_requests_enabled"`
		HasPage             bool        `json:"has_page"`
		License             string      `json:"license"`
		Outsourced          bool        `json:"outsourced"`
		ProjectCreator      string      `json:"project_creator"`
		Members             []string    `json:"members"`
		PushedAt            time.Time   `json:"pushed_at"`
		CreatedAt           time.Time   `json:"created_at"`
		UpdatedAt           time.Time   `json:"updated_at"`
		Parent              interface{} `json:"parent"`
		Paas                interface{} `json:"paas"`
		AssigneesNumber     int         `json:"assignees_number"`
		TestersNumber       int         `json:"testers_number"`
		Assignee            []struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"assignee"`
		Testers []struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"testers"`
		Status        string        `json:"status"`
		Programs      []interface{} `json:"programs"`
		Enterprise    interface{}   `json:"enterprise"`
		ProjectLabels []interface{} `json:"project_labels"`
	} `json:"parent"`
	Paas            interface{} `json:"paas"`
	AssigneesNumber int         `json:"assignees_number"`
	TestersNumber   int         `json:"testers_number"`
	Assignee        []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"assignee"`
	Testers []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"testers"`
	Status        string        `json:"status"`
	Programs      []interface{} `json:"programs"`
	Enterprise    interface{}   `json:"enterprise"`
	ProjectLabels []interface{} `json:"project_labels"`
}

type CreatePullRequestRequest struct {
	AccessToken string `json:"access_token"`
	Title       string `json:"title"`
	Head        string `json:"head"`
	Base        string `json:"base"`
	Body        string `json:"body"`
}

type RepoInfoResponse struct {
	Id        int    `json:"id"`
	FullName  string `json:"full_name"`
	HumanName string `json:"human_name"`
	Url       string `json:"url"`
	Namespace struct {
		Id      int    `json:"id"`
		Type    string `json:"type"`
		Name    string `json:"name"`
		Path    string `json:"path"`
		HtmlUrl string `json:"html_url"`
	} `json:"namespace"`
	Path  string `json:"path"`
	Name  string `json:"name"`
	Owner struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"owner"`
	Assigner struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"assigner"`
	Description         string    `json:"description"`
	Private             bool      `json:"private"`
	Public              bool      `json:"public"`
	Internal            bool      `json:"internal"`
	Fork                bool      `json:"fork"`
	HtmlUrl             string    `json:"html_url"`
	SshUrl              string    `json:"ssh_url"`
	ForksUrl            string    `json:"forks_url"`
	KeysUrl             string    `json:"keys_url"`
	CollaboratorsUrl    string    `json:"collaborators_url"`
	HooksUrl            string    `json:"hooks_url"`
	BranchesUrl         string    `json:"branches_url"`
	TagsUrl             string    `json:"tags_url"`
	BlobsUrl            string    `json:"blobs_url"`
	StargazersUrl       string    `json:"stargazers_url"`
	ContributorsUrl     string    `json:"contributors_url"`
	CommitsUrl          string    `json:"commits_url"`
	CommentsUrl         string    `json:"comments_url"`
	IssueCommentUrl     string    `json:"issue_comment_url"`
	IssuesUrl           string    `json:"issues_url"`
	PullsUrl            string    `json:"pulls_url"`
	MilestonesUrl       string    `json:"milestones_url"`
	NotificationsUrl    string    `json:"notifications_url"`
	LabelsUrl           string    `json:"labels_url"`
	ReleasesUrl         string    `json:"releases_url"`
	Recommend           bool      `json:"recommend"`
	Gvp                 bool      `json:"gvp"`
	Homepage            string    `json:"homepage"`
	Language            string    `json:"language"`
	ForksCount          int       `json:"forks_count"`
	StargazersCount     int       `json:"stargazers_count"`
	WatchersCount       int       `json:"watchers_count"`
	DefaultBranch       string    `json:"default_branch"`
	OpenIssuesCount     int       `json:"open_issues_count"`
	HasIssues           bool      `json:"has_issues"`
	HasWiki             bool      `json:"has_wiki"`
	IssueComment        bool      `json:"issue_comment"`
	CanComment          bool      `json:"can_comment"`
	PullRequestsEnabled bool      `json:"pull_requests_enabled"`
	HasPage             bool      `json:"has_page"`
	License             string    `json:"license"`
	Outsourced          bool      `json:"outsourced"`
	ProjectCreator      string    `json:"project_creator"`
	Members             []string  `json:"members"`
	PushedAt            time.Time `json:"pushed_at"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	Parent              struct {
		Id        int    `json:"id"`
		FullName  string `json:"full_name"`
		HumanName string `json:"human_name"`
		Url       string `json:"url"`
		Namespace struct {
			Id      int    `json:"id"`
			Type    string `json:"type"`
			Name    string `json:"name"`
			Path    string `json:"path"`
			HtmlUrl string `json:"html_url"`
		} `json:"namespace"`
		Path  string `json:"path"`
		Name  string `json:"name"`
		Owner struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"owner"`
		Assigner struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"assigner"`
		Description         string      `json:"description"`
		Private             bool        `json:"private"`
		Public              bool        `json:"public"`
		Internal            bool        `json:"internal"`
		Fork                bool        `json:"fork"`
		HtmlUrl             string      `json:"html_url"`
		SshUrl              string      `json:"ssh_url"`
		ForksUrl            string      `json:"forks_url"`
		KeysUrl             string      `json:"keys_url"`
		CollaboratorsUrl    string      `json:"collaborators_url"`
		HooksUrl            string      `json:"hooks_url"`
		BranchesUrl         string      `json:"branches_url"`
		TagsUrl             string      `json:"tags_url"`
		BlobsUrl            string      `json:"blobs_url"`
		StargazersUrl       string      `json:"stargazers_url"`
		ContributorsUrl     string      `json:"contributors_url"`
		CommitsUrl          string      `json:"commits_url"`
		CommentsUrl         string      `json:"comments_url"`
		IssueCommentUrl     string      `json:"issue_comment_url"`
		IssuesUrl           string      `json:"issues_url"`
		PullsUrl            string      `json:"pulls_url"`
		MilestonesUrl       string      `json:"milestones_url"`
		NotificationsUrl    string      `json:"notifications_url"`
		LabelsUrl           string      `json:"labels_url"`
		ReleasesUrl         string      `json:"releases_url"`
		Recommend           bool        `json:"recommend"`
		Gvp                 bool        `json:"gvp"`
		Homepage            string      `json:"homepage"`
		Language            string      `json:"language"`
		ForksCount          int         `json:"forks_count"`
		StargazersCount     int         `json:"stargazers_count"`
		WatchersCount       int         `json:"watchers_count"`
		DefaultBranch       string      `json:"default_branch"`
		OpenIssuesCount     int         `json:"open_issues_count"`
		HasIssues           bool        `json:"has_issues"`
		HasWiki             bool        `json:"has_wiki"`
		IssueComment        bool        `json:"issue_comment"`
		CanComment          bool        `json:"can_comment"`
		PullRequestsEnabled bool        `json:"pull_requests_enabled"`
		HasPage             bool        `json:"has_page"`
		License             string      `json:"license"`
		Outsourced          bool        `json:"outsourced"`
		ProjectCreator      string      `json:"project_creator"`
		Members             []string    `json:"members"`
		PushedAt            time.Time   `json:"pushed_at"`
		CreatedAt           time.Time   `json:"created_at"`
		UpdatedAt           time.Time   `json:"updated_at"`
		Parent              interface{} `json:"parent"`
		Paas                interface{} `json:"paas"`
		AssigneesNumber     int         `json:"assignees_number"`
		TestersNumber       int         `json:"testers_number"`
		Assignee            []struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"assignee"`
		Testers []struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"testers"`
		Status        string        `json:"status"`
		Programs      []interface{} `json:"programs"`
		Enterprise    interface{}   `json:"enterprise"`
		ProjectLabels []interface{} `json:"project_labels"`
	} `json:"parent"`
	Paas            interface{} `json:"paas"`
	AssigneesNumber int         `json:"assignees_number"`
	TestersNumber   int         `json:"testers_number"`
	Assignee        []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"assignee"`
	Testers []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"testers"`
	Status        string        `json:"status"`
	Programs      []interface{} `json:"programs"`
	Enterprise    interface{}   `json:"enterprise"`
	ProjectLabels []interface{} `json:"project_labels"`
}

type CreatePullResponse struct {
	Id                int    `json:"id"`
	Url               string `json:"url"`
	HtmlUrl           string `json:"html_url"`
	DiffUrl           string `json:"diff_url"`
	PatchUrl          string `json:"patch_url"`
	IssueUrl          string `json:"issue_url"`
	CommitsUrl        string `json:"commits_url"`
	ReviewCommentsUrl string `json:"review_comments_url"`
	ReviewCommentUrl  string `json:"review_comment_url"`
	CommentsUrl       string `json:"comments_url"`
	Number            int    `json:"number"`
	State             string `json:"state"`
	AssigneesNumber   int    `json:"assignees_number"`
	TestersNumber     int    `json:"testers_number"`
	Assignees         []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
		Assignee          bool   `json:"assignee"`
		CodeOwner         bool   `json:"code_owner"`
		Accept            bool   `json:"accept"`
	} `json:"assignees"`
	Testers []struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
		Assignee          bool   `json:"assignee"`
		CodeOwner         bool   `json:"code_owner"`
		Accept            bool   `json:"accept"`
	} `json:"testers"`
	Milestone     interface{}   `json:"milestone"`
	Labels        []interface{} `json:"labels"`
	Locked        bool          `json:"locked"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	ClosedAt      interface{}   `json:"closed_at"`
	Draft         bool          `json:"draft"`
	MergedAt      interface{}   `json:"merged_at"`
	Mergeable     bool          `json:"mergeable"`
	CanMergeCheck bool          `json:"can_merge_check"`
	Links         struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
		Html struct {
			Href string `json:"href"`
		} `json:"html"`
		Issue struct {
			Href string `json:"href"`
		} `json:"issue"`
		Comments struct {
			Href string `json:"href"`
		} `json:"comments"`
		ReviewComments struct {
			Href string `json:"href"`
		} `json:"review_comments"`
		ReviewComment struct {
			Href string `json:"href"`
		} `json:"review_comment"`
		Commits struct {
			Href string `json:"href"`
		} `json:"commits"`
	} `json:"_links"`
	User struct {
		Id                int    `json:"id"`
		Login             string `json:"login"`
		Name              string `json:"name"`
		AvatarUrl         string `json:"avatar_url"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		Remark            string `json:"remark"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
	} `json:"user"`
	RefPullRequests []interface{} `json:"ref_pull_requests"`
	Title           string        `json:"title"`
	Body            string        `json:"body"`
	Head            struct {
		Label string `json:"label"`
		Ref   string `json:"ref"`
		Sha   string `json:"sha"`
		User  struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"user"`
		Repo struct {
			Id        int    `json:"id"`
			FullName  string `json:"full_name"`
			HumanName string `json:"human_name"`
			Url       string `json:"url"`
			Namespace struct {
				Id      int    `json:"id"`
				Type    string `json:"type"`
				Name    string `json:"name"`
				Path    string `json:"path"`
				HtmlUrl string `json:"html_url"`
			} `json:"namespace"`
			Path  string `json:"path"`
			Name  string `json:"name"`
			Owner struct {
				Id                int    `json:"id"`
				Login             string `json:"login"`
				Name              string `json:"name"`
				AvatarUrl         string `json:"avatar_url"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				Remark            string `json:"remark"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
			} `json:"owner"`
			Assigner struct {
				Id                int    `json:"id"`
				Login             string `json:"login"`
				Name              string `json:"name"`
				AvatarUrl         string `json:"avatar_url"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				Remark            string `json:"remark"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
			} `json:"assigner"`
			Description string `json:"description"`
			Private     bool   `json:"private"`
			Public      bool   `json:"public"`
			Internal    bool   `json:"internal"`
			Fork        bool   `json:"fork"`
			HtmlUrl     string `json:"html_url"`
			SshUrl      string `json:"ssh_url"`
		} `json:"repo"`
	} `json:"head"`
	Base struct {
		Label string `json:"label"`
		Ref   string `json:"ref"`
		Sha   string `json:"sha"`
		User  struct {
			Id                int    `json:"id"`
			Login             string `json:"login"`
			Name              string `json:"name"`
			AvatarUrl         string `json:"avatar_url"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			Remark            string `json:"remark"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
		} `json:"user"`
		Repo struct {
			Id        int    `json:"id"`
			FullName  string `json:"full_name"`
			HumanName string `json:"human_name"`
			Url       string `json:"url"`
			Namespace struct {
				Id      int    `json:"id"`
				Type    string `json:"type"`
				Name    string `json:"name"`
				Path    string `json:"path"`
				HtmlUrl string `json:"html_url"`
			} `json:"namespace"`
			Path  string `json:"path"`
			Name  string `json:"name"`
			Owner struct {
				Id                int    `json:"id"`
				Login             string `json:"login"`
				Name              string `json:"name"`
				AvatarUrl         string `json:"avatar_url"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				Remark            string `json:"remark"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
			} `json:"owner"`
			Assigner struct {
				Id                int    `json:"id"`
				Login             string `json:"login"`
				Name              string `json:"name"`
				AvatarUrl         string `json:"avatar_url"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				Remark            string `json:"remark"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
			} `json:"assigner"`
			Description string `json:"description"`
			Private     bool   `json:"private"`
			Public      bool   `json:"public"`
			Internal    bool   `json:"internal"`
			Fork        bool   `json:"fork"`
			HtmlUrl     string `json:"html_url"`
			SshUrl      string `json:"ssh_url"`
		} `json:"repo"`
	} `json:"base"`
}